version: '3.9'

services:
  db:
    image: postgis/postgis:17-3.4
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: shortnr_prod
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MIX_ENV: prod
      PHX_HOST: localhost
      PHX_SERVER: "true"
      SECRET_KEY_BASE: change_me_with_mix_phx_gen_secret
      DATABASE_URL: ecto://postgres:postgres@db/shortnr_prod
      SLUG_SECRET: change_me_for_slugs
    command: /bin/sh -c "/app/bin/shortnr eval \"Shortnr.Release.migrate\" && /app/bin/shortnr start"
    ports:
      - "4000:4000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:

